import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bagoss = localFont({
  src: "./fonts/BagossTRIALVF.ttf",
  variable: "--font-bagoss",
  display: "swap",
});

const sohne = localFont({
  src: "./fonts/Sohne-Buch.otf",
  variable: "--font-sohne",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bagoss.variable} ${sohne.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
